# -*- coding: utf-8 -*-
"""Ejercios_clase_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XMWUcLz_mWaXb8BwMwWgm1qAZ4UGysvV
"""

#INSUMO PRELIMINAR GENERACION .CSV

import pandas as pd
import requests
from pandas.testing import assert_frame_equal


# Creamos el CSV del Catálogo Territorial con datos sucios
csv_catalogo = """id,codigo_dpa,provincia,pacientes_atendidos
1,1701,Pichincha,45
2,0901,Guayas,Sin dato
3,0101,Azuay,120
4,1701,Pichincha,N/A
5,0901,Guayas,80
6,0701,El Oro,95
7,1101,Loja,Sin dato
8,1701,Pichincha,150
9,0901,Guayas,200
10,0101,Azuay,110
"""
with open('catalogo_territorial.csv', 'w') as f:
    f.write(csv_catalogo)

print("¡Archivo 'catalogo_territorial.csv' generado listo para procesar!")

"""**1. Extracción desde la API**"""

# Petición ingenua: Sin timeout y asumiendo éxito directo
url_api = "https://jsonplaceholder.typicode.com/users"
respuesta = requests.get(url_api)  # 💥 Si el servidor no responde, se cuelga indefinidamente
timeout_segundos = 10

try:
  respuesta = requests.get(url_api, timeout=timeout_segundos)

  # Validación estricta del código HTTP (200 OK)
  if respuesta.status_code == 200:
    datos_validos = respuesta.json()
    print(
        f"✅ Extracción Exitosa [HTTP {respuesta.status_code}]:"
        f" {len(datos_validos)} registros cargados."
    )
  else:
    print(
        f"⚠️ Falla del Servidor [HTTP {respuesta.status_code}]: Registro de"
        " error generado."
    )

except requests.exceptions.Timeout:
  print("Error de Red: Se superó el tiempo límite de espera (Timeout).")
except requests.exceptions.RequestException as e:
  print(f"Error crítico en la petición API: {e}")

"""**Aplanamiento**"""

df_aplanado = pd.json_normalize(datos_validos)

print("Matriz bidimensional aplanada correctamente:")
print(df_aplanado)
print("\nEncabezados extraídos:", df_aplanado.columns.tolist())

"""**2. Lectura Segura del CSV**"""

df_catalogo = pd.read_csv(
    'catalogo_territorial.csv',
    dtype={'codigo_dpa': str}
)
df_catalogo

"""**3. Integración**"""

df_merged = pd.merge(
    df_aplanado,
    df_catalogo,
    on='id',
    how='inner',
    validate='one_to_one'
)


df_merged['pacientes_atendidos'] = pd.to_numeric(
    df_merged['pacientes_atendidos'],
    errors='coerce'
)

# Reporte de calidad post-sanitización
nulos = df_merged['pacientes_atendidos'].isna().sum()
validos = df_merged['pacientes_atendidos'].notna().sum()

print(f'Nulos: {nulos}')
print(f'Validos: {validos}')

df_merged

"""**Sanitización**"""

df_final = df_merged.dropna(subset=['pacientes_atendidos']).copy()
df_final

"""**4. Exportación Profesional**"""

OUTPUT_FILE = 'usuarios_limpios.parquet'

df_final.to_parquet(OUTPUT_FILE, index=False, engine='pyarrow')
df_final = df_final.reset_index(drop=True)


OUTPUT_FILE


df_parquet = pd.read_parquet(OUTPUT_FILE)
print("Estructura de carpetas creada y Parquet exportado.")
print("Dtypes preservados de forma nativa:\n", df_parquet.dtypes)

"""**Validación**"""

assert df_parquet.shape == df_final.shape, "Error: el archivo exportado no coincide"
assert_frame_equal(df_parquet, df_final, check_dtype=False)

"""**Arquitectura de capas**"""

from pathlib import Path

# 1. Creación programática de la arquitectura de capas
base_dir = Path("proyecto_analitico/data")
for capa in ["raw", "interim", "processed"]:
  (base_dir / capa).mkdir(parents=True, exist_ok=True)

# 2. Guardado en Bóveda Analítica como Parquet (Preserva dtypes estrictamente)
ruta_parquet = base_dir / "processed" / "usuarios_limpios.parquet"
df_final.to_parquet(ruta_parquet, index=False)

ruta_raw = base_dir / "raw" / "catalogo_territorial.csv"
df_catalogo.to_csv(ruta_raw, index=False, encoding="utf-8")

ruta_interim = base_dir / "interim" / "df_merged.csv"
df_merged.to_csv(ruta_interim, index=False, encoding="utf-8")

"""**Muestra .parquet**"""

df_parquet = pd.read_parquet("usuarios_limpios.parquet")
df_parquet